### ISSUE TITLE
Custom styles are not always rendered

### ISSUE THREAD

**Issue by zslabs** [SimonSiefke/vscode-svg-preview#12]
@SimonSiefke When opening multiple icons (after closing other previews) custom styles will not render, only showing the default background. I also noticed while recording this, that the auto opener did not work the first time, which was a bit odd. This was after a fresh restart of VS Code.

![Kapture 2019-05-18 at 19 43 41](https://user-images.githubusercontent.com/1018402/57976047-58ecf600-79a5-11e9-8128-14b40715208d.gif)

**Comment by SimonSiefke** [comment]
The custom styles issue has been fixed. The other issue occurs when an svg is opened before the extension is activated, the reason that is doesn't automatically open is that there might already be a svg webview panel which gets restored and then there would be two preview panels which shouldn't happen. I will close this for now, because I don't think there is anything I can currently do about.

**Comment by zslabs** [comment]
Thanks for taking a look at these issues the past few days, really appreciate it!
